name: vikrf_thesis
description: "vikrf_thesis"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_strategy: ^0.3.0
  get_it: ^8.0.0
  uuid: ^4.5.0
  go_router: ^14.2.7
  flutter_bloc: ^8.1.6
  dio: ^5.7.0

  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.0
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  dartx: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/bgs/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf
